import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./shared/contexts/auth";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ModalProvider } from "./shared/contexts/modals";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Xtreme Tools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/ico" href="/x_logo.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>xtreme-tools</title>
      </head>
      <body className={""}>
        <NextTopLoader color="#58126A" />
        <ModalProvider>
          <AuthProvider>
            <div className="min-h-screen bg-white flex flex-col">
              {children}
            </div>
            <div id="modal-root"></div>
          </AuthProvider>
        </ModalProvider>
        <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
